### Create User1
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Robert Jensen",
  "email": "robert@robert-jensen.dk",
  "company": "VMware"
}

### Create User2
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jdoe@missing.com",
  "company": "WeFindYou"
}

### Get Users

GET http://localhost:8080/api/users