apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: api
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: tanzuquiz
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  serviceClaims:
    - name: tanzuquiz-db
      ref:
        apiVersion: v1
        kind: Secret
        name: tanzuquiz-db-secret
  source:
    git:
      url: https://github.com/TanzuDK/TanzuQuiz.git
      ref:
        branch: main
    subPath: api
