apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: quiz-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzuquiz
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/min-scale: "1"
  source:
    git:
      url: https://github.com/TanzuDK/TanzuQuiz.git
      ref:
        branch: main
    subPath: frontend
