apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quiz-frontend
  description: The frontend for the Tanzu Quiz Application
  tags:
    - golang
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=tanzuquiz
spec:
  type: api
  lifecycle: production
  owner: denmark-team
  system: tanzuquiz
  dependsOn:
    - component:default/api
