apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: tanzuquiz
  namespace: default
spec:
  postgresVersion:
    name: postgres-14
  serviceType: ClusterIP
  highAvailability:
    enabled: true
  pgConfig:
    dbname: tanzuquiz
    username: pgadmin
    appUser: pgappuser
    readOnlyUser: pgrouser
    readWriteUser: pgrwuser
  imagePullSecret:
    name: tap-registry
  persistentVolumeClaimPolicy: delete
  storageSize: 2Gi
  monitorStorageSize: 1G
  resources:
    data:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 100Mi
    monitor:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 100Mi
    metrics:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
